export const LOGIN_SUCCESS="LOGIN_SUCCESS"
export const LOGIN_FAIL="LOGIN_FAIL"
export const LOGIN_REQUEST="LOGIN_REQUEST"
export const LOG_OUT="LOG_OUT"
export const LOAD_PROFILE="LOAD_PROFILE"

export const HOME_VIDEO_SUCCESS="HOME_VIDEO_SUCCESS"
export const HOME_VIDEO_FAIL="HOME_VIDEO_FAIL"
export const HOME_VIDEO_REQUEST="HOME_VIDEO_REQUEST"

export const SELECTED_VIDEOS_REQUEST="SELECTED_VIDEOS_REQUEST"
export const SELECTED_VIDEOS_SUCCESS="SELECTED_VIDEOS_SUCCESS"
export const SELECTED_VIDEOS_FAIL="SELECTED_VIDEOS_FAIL"

export const CHANNEL_DETAIL_REQUEST="CHANNEL_DETAIL_REQUEST"
export const CHANNEL_DETAIL_SUCCESS="CHANNEL_DETAIL_SUCCESS"
export const CHANNEL_DETAIL_FAIL="CHANNEL_DETAIL_FAIL"

export const SET_SUBSCRIPTIOJN_STATUS="SET_SUBSCRIPTIOJN_STATUS";

export const COMMENT_LIST_REQUEST="COMMENT_LIST_REQUEST"
export const COMMENT_LIST_SUCCESS="COMMENT_LIST_SUCCESS"
export const COMMENT_LIST_FAIL="COMMENT_LIST_FAIL"

export const CREATE_COMMENT_SUCCCESS="CREATE_COMMENT_SUCCCESS"
export const CREATE_COMMENT_FAIL="CREATE_COMMENT_FAIL"

export const RELATED_VIDEO_REQUEST="RELATED_VIDEO_REQUEST"
export const RELATED_VIDEO_SUCCESS="RELATED_VIDEO_SUCCESS"
export const RELATED_VIDEO_FAIL="RELATED_VIDEO_FAIL"

export const SEARCHED_VIDEO_REQUEST="SEARCHED_VIDEO_REQUEST"
export const SEARCHED_VIDEO_SUCCESS="SEARCHED_VIDEO_SUCCESS"
export const SEARCHED_VIDEO_FAIL="SEARCHED_VIDEO_FAIL"

export const SUBSCRIPTION_CHANNEL_REQUEST="SUBSCRIPTION_CHANNEL_REQUEST"
export const SUBSCRIPTION_CHANNEL_SUCCESS="SUBSCRIPTION_CHANNEL_SUCCESS"
export const SUBSCRIPTION_CHANNEL_FAIL="SUBSCRIPTION_CHANNEL_FAIL"

export const CHANNEL_VIDEO_REQUEST="CHANNEL_VIDEO_REQUEST"
export const CHANNEL_VIDEO_SUCCESS="CHANNEL_VIDEO_SUCCESS"
export const CHANNEL_VIDEO_FAIL="CHANNEL_VIDEO_FAIL"

